import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdateFn(() => new Date()),
};

/** Last state reported by the device in its heartbeat. */
export interface DeviceStatus {
  battery?: { level: number; charging: boolean } | null;
  wifi?: { rssi: number; ssid?: string | null; linkSpeedMbps?: number | null } | null;
  currentUrl?: string | null;
  uptimeSeconds?: number | null;
  appVersion?: string | null;
}

export type ScreenSource = "builtin" | "user" | "ai";
export type AssignmentType = "none" | "screen" | "playlist";

export const screens = sqliteTable("screens", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description").notNull().default(""),
  /** Body fragment: markup plus inline <style>/<script>. See docs/screen-authoring.md. */
  html: text("html").notNull(),
  source: text("source").$type<ScreenSource>().notNull().default("user"),
  /** Most recent natural-language prompt used to generate/iterate this screen (Phase 4). */
  generationPrompt: text("generation_prompt"),
  /** How often the kiosk runtime refetches kiosk.data while this screen is shown. */
  dataRefreshSeconds: integer("data_refresh_seconds").notNull().default(60),
  ...timestamps,
});

export const playlists = sqliteTable("playlists", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  ...timestamps,
});

export const playlistItems = sqliteTable(
  "playlist_items",
  {
    id: text("id").primaryKey(),
    playlistId: text("playlist_id")
      .notNull()
      .references(() => playlists.id, { onDelete: "cascade" }),
    screenId: text("screen_id")
      .notNull()
      .references(() => screens.id, { onDelete: "restrict" }),
    position: integer("position").notNull(),
    dwellSeconds: integer("dwell_seconds").notNull(),
  },
  (t) => [uniqueIndex("playlist_items_playlist_position").on(t.playlistId, t.position)],
);

export const devices = sqliteTable(
  "devices",
  {
    /** UUID generated by the device on first run. */
    id: text("id").primaryKey(),
    name: text("name"),
    /** Shown on unclaimed devices; null once claimed. */
    pairingCode: text("pairing_code"),
    claimedAt: integer("claimed_at", { mode: "timestamp_ms" }),
    /** SHA-256 of the current device token. Rotated on every registration. */
    tokenHash: text("token_hash").notNull(),
    model: text("model").notNull(),
    androidVersion: text("android_version").notNull(),
    appVersion: text("app_version").notNull(),
    screenWidth: integer("screen_width").notNull(),
    screenHeight: integer("screen_height").notNull(),
    assignmentType: text("assignment_type").$type<AssignmentType>().notNull().default("none"),
    screenId: text("screen_id").references(() => screens.id, { onDelete: "set null" }),
    playlistId: text("playlist_id").references(() => playlists.id, { onDelete: "set null" }),
    /** Screen the device is currently told to render (single screen, or current playlist item). */
    currentScreenId: text("current_screen_id").references(() => screens.id, { onDelete: "set null" }),
    playlistPosition: integer("playlist_position").notNull().default(0),
    lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }),
    lastIp: text("last_ip"),
    status: text("status", { mode: "json" }).$type<DeviceStatus>().notNull().default({}),
    registeredAt: integer("registered_at", { mode: "timestamp_ms" }).notNull(),
    ...timestamps,
  },
  (t) => [uniqueIndex("devices_pairing_code").on(t.pairingCode)],
);

export type LogLevel = "error" | "warn" | "info";

export interface DeviceLogContext {
  source?: string | null;
  line?: number | null;
  column?: number | null;
  stack?: string | null;
  url?: string | null;
  screenId?: string | null;
  userAgent?: string | null;
}

export const deviceLogs = sqliteTable(
  "device_logs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    deviceId: text("device_id")
      .notNull()
      .references(() => devices.id, { onDelete: "cascade" }),
    level: text("level").$type<LogLevel>().notNull(),
    message: text("message").notNull(),
    context: text("context", { mode: "json" }).$type<DeviceLogContext>().notNull().default({}),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (t) => [index("device_logs_device_created").on(t.deviceId, t.createdAt)],
);

export type Screen = typeof screens.$inferSelect;
export type Playlist = typeof playlists.$inferSelect;
export type PlaylistItem = typeof playlistItems.$inferSelect;
export type Device = typeof devices.$inferSelect;
export type DeviceLog = typeof deviceLogs.$inferSelect;
