/**
 * Request body / query types for every /api route.
 * `schemas.ts` holds the matching Zod schemas; the two must stay in sync
 * (schemas.test.ts checks this at the type level).
 */

// ---- Auth ----------------------------------------------------------------

export interface LoginRequest {
  /** 1-1024 chars. */
  password: string;
}

// ---- Device-facing -------------------------------------------------------

export interface RegisterDeviceRequest {
  /** UUID generated by the device on first run (any RFC 4122 version). */
  deviceId: string;
  /** 1-100 chars, e.g. "Echo_Show_8". */
  model: string;
  /** 1-32 chars, e.g. "11". */
  androidVersion: string;
  /** 1-32 chars, e.g. "0.1.0". */
  appVersion: string;
  /** Physical pixels, integer 1-10000. */
  screenWidth: number;
  /** Physical pixels, integer 1-10000. */
  screenHeight: number;
}

export interface HeartbeatRequest {
  /** level: integer 0-100. Omit or null when unknown. */
  battery?: { level: number; charging: boolean } | null;
  /** rssi: integer dBm -127..0; ssid: max 64 chars; linkSpeedMbps: integer 0-100000. */
  wifi?: { rssi: number; ssid?: string | null; linkSpeedMbps?: number | null } | null;
  /** URL the WebView is showing, max 2048 chars. */
  currentUrl?: string | null;
  /** Screen id the page reports it is rendering, max 100 chars. */
  currentScreenId?: string | null;
  /** Integer >= 0. */
  uptimeSeconds?: number | null;
  /** How the app is holding the screen: launcher (default Home app), strict (device owner lock task), immersive (neither). */
  kioskMode?: KioskMode | null;
  /** Whether ShowRunner is the device's default Home app. */
  isDefaultHome?: boolean | null;
}

export type KioskMode = "launcher" | "strict" | "immersive";

/** Commands handled by the Android app itself (delivered in the heartbeat reply, never via screen JavaScript). */
export type NativeCommandType = "openExitMenu" | "openSettings" | "exitStrictMode";

export interface DeviceLogRequest {
  /** Defaults to "error". */
  level?: "error" | "warn" | "info";
  /** 1-4000 chars. */
  message: string;
  /** max 2048 chars. */
  source?: string | null;
  /** Integer >= 0. */
  line?: number | null;
  /** Integer >= 0. */
  column?: number | null;
  /** max 16000 chars. */
  stack?: string | null;
  /** max 2048 chars. */
  url?: string | null;
  /** max 100 chars. */
  screenId?: string | null;
}

// ---- Admin: devices --------------------------------------------------------

export interface ClaimDeviceRequest {
  /** 6 chars from the pairing alphabet A-H J K M N P-Z 2-9 (no I, L, O, 0, 1); case-insensitive, trimmed. */
  pairingCode: string;
  /** 1-100 chars, trimmed. */
  name: string;
}

export type DeviceAssignment =
  | { type: "none" }
  | { type: "screen"; /** 1-100 chars */ screenId: string }
  | { type: "playlist"; /** 1-100 chars */ playlistId: string };

export interface UpdateDeviceRequest {
  /** 1-100 chars, trimmed. */
  name?: string;
  assignment?: DeviceAssignment;
}

export type DeviceCommandRequest =
  | { type: "reload" }
  | { type: "refreshData" }
  | { type: "navigate"; /** 1-100 chars */ screenId: string }
  | { type: NativeCommandType };

export interface DeviceLogsQuery {
  /** Integer 1-500, default 100. Parsed from a query string, so coerce. */
  limit: number;
  /** Only logs with id < before (pagination). Integer >= 1, optional. Coerced. */
  before?: number;
}

// ---- Admin: screens --------------------------------------------------------

export interface CreateScreenRequest {
  /** 1-100 chars, trimmed. */
  name: string;
  /** max 500 chars, default "". */
  description?: string;
  /** 1 to 512000 chars. */
  html: string;
  /** Integer 5-3600, default 60. */
  dataRefreshSeconds?: number;
  /** Only "user" or "ai" may be set through the API; default "user". */
  source?: "user" | "ai";
  /** max 4000 chars. */
  generationPrompt?: string | null;
}

/** Every field optional, same constraints as create; at least one field required. */
export type UpdateScreenRequest = Partial<CreateScreenRequest>;

// ---- Admin: playlists ------------------------------------------------------

export interface PlaylistItemInput {
  /** 1-100 chars. */
  screenId: string;
  /** Integer 5-86400. */
  dwellSeconds: number;
}

export interface CreatePlaylistRequest {
  /** 1-100 chars, trimmed. */
  name: string;
  /** Order is play order. 0-200 items, default []. */
  items?: PlaylistItemInput[];
}

/** Both optional; at least one required. `items` replaces the whole list. */
export interface UpdatePlaylistRequest {
  name?: string;
  items?: PlaylistItemInput[];
}

// ---- Admin: settings ---------------------------------------------------------

/**
 * Overrides for env-var defaults (WEATHER_LAT, WEATHER_LON, WEATHER_UNITS, KIOSK_TIMEZONE).
 * Every field optional; `null` clears the override (back to the env default). At least one field required.
 */
export interface UpdateSettingsRequest {
  /** Number -90..90, or null. */
  weatherLatitude?: number | null;
  /** Number -180..180, or null. */
  weatherLongitude?: number | null;
  /** "imperial" | "metric", or null. */
  weatherUnits?: "imperial" | "metric" | null;
  /** Display label for the location, e.g. "Los Angeles, California". Trimmed, 1-100 chars, or null. */
  weatherLocationName?: string | null;
  /** IANA timezone accepted by Intl.DateTimeFormat (e.g. "America/Los_Angeles"), or null. */
  timezone?: string | null;
  /** PIN for the on-device kiosk exit menu: 4-8 digits, or null to remove it (menu opens without a PIN). */
  kioskExitPin?: string | null;
}

export interface GeocodeQuery {
  /** Place name to search. Trimmed, 2-100 chars. */
  q: string;
}

// ---- Admin: AI screen generation ---------------------------------------------------

export interface GenerateScreenRequest {
  /** What to build or change, in plain English. Trimmed, 1-4000 chars. */
  instruction: string;
  /** The current template to modify ("based on current screen"). Up to 512000 chars, or null/omitted for a new screen. */
  currentHtml?: string | null;
  /** Model id for the configured provider, e.g. "google/gemini-3.8-flash". Trimmed, 1-200 chars. Omit for the server default. */
  model?: string;
  /** JS errors the editor preview reported for currentHtml, passed to the model. 0-20 items, each 1-1000 chars. */
  previewErrors?: string[];
}
