/**
 * Request body / query types for every /api route.
 * `schemas.ts` holds the matching Zod schemas; the two must stay in sync
 * (schemas.test.ts checks this at the type level).
 */

// ---- Auth ----------------------------------------------------------------

export interface LoginRequest {
  /** 1-1024 chars. */
  password: string;
}

// ---- Device-facing -------------------------------------------------------

export interface RegisterDeviceRequest {
  /** UUID generated by the device on first run (any RFC 4122 version). */
  deviceId: string;
  /** 1-100 chars, e.g. "Echo_Show_8". */
  model: string;
  /** 1-32 chars, e.g. "11". */
  androidVersion: string;
  /** 1-32 chars, e.g. "0.1.0". */
  appVersion: string;
  /** Physical pixels, integer 1-10000. */
  screenWidth: number;
  /** Physical pixels, integer 1-10000. */
  screenHeight: number;
}

export interface HeartbeatRequest {
  /** level: integer 0-100. Omit or null when unknown. */
  battery?: { level: number; charging: boolean } | null;
  /** rssi: integer dBm -127..0; ssid: max 64 chars; linkSpeedMbps: integer 0-100000. */
  wifi?: { rssi: number; ssid?: string | null; linkSpeedMbps?: number | null } | null;
  /** URL the WebView is showing, max 2048 chars. */
  currentUrl?: string | null;
  /** Screen id the page reports it is rendering, max 100 chars. */
  currentScreenId?: string | null;
  /** Integer >= 0. */
  uptimeSeconds?: number | null;
}

export interface DeviceLogRequest {
  /** Defaults to "error". */
  level?: "error" | "warn" | "info";
  /** 1-4000 chars. */
  message: string;
  /** max 2048 chars. */
  source?: string | null;
  /** Integer >= 0. */
  line?: number | null;
  /** Integer >= 0. */
  column?: number | null;
  /** max 16000 chars. */
  stack?: string | null;
  /** max 2048 chars. */
  url?: string | null;
  /** max 100 chars. */
  screenId?: string | null;
}

// ---- Admin: devices --------------------------------------------------------

export interface ClaimDeviceRequest {
  /** 6 chars from the pairing alphabet; accepted case-insensitively and trimmed. */
  pairingCode: string;
  /** 1-100 chars, trimmed. */
  name: string;
}

export type DeviceAssignment =
  | { type: "none" }
  | { type: "screen"; screenId: string }
  | { type: "playlist"; playlistId: string };

export interface UpdateDeviceRequest {
  /** 1-100 chars, trimmed. */
  name?: string;
  assignment?: DeviceAssignment;
}

export type DeviceCommandRequest =
  | { type: "reload" }
  | { type: "refreshData" }
  | { type: "navigate"; screenId: string };

export interface DeviceLogsQuery {
  /** Integer 1-500, default 100. Parsed from a query string, so coerce. */
  limit: number;
  /** Only logs with id < before (pagination). Integer >= 1, optional. Coerced. */
  before?: number;
}

// ---- Admin: screens --------------------------------------------------------

export interface CreateScreenRequest {
  /** 1-100 chars, trimmed. */
  name: string;
  /** max 500 chars, default "". */
  description?: string;
  /** 1 to 512000 chars. */
  html: string;
  /** Integer 5-3600, default 60. */
  dataRefreshSeconds?: number;
  /** Only "user" or "ai" may be set through the API; default "user". */
  source?: "user" | "ai";
  /** max 4000 chars. */
  generationPrompt?: string | null;
}

/** Every field optional, same constraints as create; at least one field required. */
export type UpdateScreenRequest = Partial<CreateScreenRequest>;

// ---- Admin: playlists ------------------------------------------------------

export interface PlaylistItemInput {
  /** 1-100 chars. */
  screenId: string;
  /** Integer 5-86400. */
  dwellSeconds: number;
}

export interface CreatePlaylistRequest {
  /** 1-100 chars, trimmed. */
  name: string;
  /** Order is play order. 0-200 items, default []. */
  items?: PlaylistItemInput[];
}

/** Both optional; at least one required. `items` replaces the whole list. */
export interface UpdatePlaylistRequest {
  name?: string;
  items?: PlaylistItemInput[];
}
